base_url = "https://bobrockefeller.com"

title = "Bob Rockefeller"
description = "What is Bob up to now?"

compile_sass = true

build_search_index = false

taxonomies = [
  {name = "tags", paginate_by = 4},
  {name = "categories", paginate_by = 4},
]

[markdown]
  # Whether to do syntax highlighting
  # Theme can be customized by setting the `highlight_theme` variable to a theme supported by Zola
  highlight_code = true
  highlight_theme = "one-dark"
  external_links_target_blank = true
  external_links_no_follow = true
  smart_punctuation = true
  definition_list = true

[extra]

menus = [
  { name = "Home", url = "/", trailing_slash = true },
  { name = "About", url = "/about/", trailing_slash = true },
  { name = "Categories", url = "/categories/", trailing_slash = true },
  { name = "Tags", url = "/tags/", trailing_slash = true }
]
